import type { CandidateStub } from "./ranking";

const avatarUrl = (seed: string) =>
  `https://api.dicebear.com/7.x/notionists/svg?seed=${encodeURIComponent(seed)}`;

const companyLogo = (domain: string) => `https://logo.clearbit.com/${domain}`;

export const candidateStubs: CandidateStub[] = [
  {
    slug: "maya-chen",
    fullName: "Maya Chen",
    headline: "Staff Full-Stack Engineer building realtime developer tools",
    summary:
      "Builds developer-facing products with React, TypeScript, and realtime backends. Has led product and infra work for collaboration features and observable systems.",
    location: "London, UK",
    currentCompany: "Mergeboard",
    profileUrl: "https://www.linkedin.com/in/maya-chen-example",
    email: "maya@example.com",
    warmIntroPath: "You -> Ravi (angel) -> Maya",
    age: 34,
    yearsExperience: 11,
    seniority: "staff",
    stacks: ["React", "TypeScript", "Convex", "Node.js", "Postgres", "WebSockets"],
    domains: ["devtools", "realtime", "collaboration"],
    roleKeywords: ["staff engineer", "full-stack", "developer tools", "realtime systems"],
    signalConfidence: 0.92,
    reachabilityScore: 0.8,
    companyLogoUrl: companyLogo("mergeboard.com"),
    socialGithub: "github.com/maya-chen",
    socialBlog: "mayachen.dev",
    socialTwitter: "@mayac",
    networkConnections: [
      {
        id: "maya-c1",
        name: "Ravi Patel",
        avatar: avatarUrl("ravi-patel"),
        role: "angel investor",
        channels: [{ type: "company", detail: "warm intro through portfolio" }],
        strength: "strong",
        lastInteraction: "3 weeks ago",
        sharedProjects: 2,
        relationship: "investor",
      },
      {
        id: "maya-c2",
        name: "Clara Olsen",
        avatar: avatarUrl("clara-olsen"),
        role: "staff engineer @ mergeboard",
        channels: [
          { type: "github", detail: "co-maintained realtime infra" },
          { type: "slack", detail: "platform guild" },
        ],
        strength: "medium",
        lastInteraction: "2 months ago",
        sharedProjects: 3,
        relationship: "colleague",
      },
    ],
    evidence: [
      {
        evidenceId: "maya-repo-realtime-presence",
        kind: "repo",
        title: "Presence service for multiplayer editing",
        snippet:
          "Led a production presence and cursor-sync service handling high fan-out collaboration sessions.",
        url: "https://github.com/example/maya/presence-service",
        strength: 0.96,
        recencyYears: 0.4,
        tags: ["realtime", "websockets", "collaboration", "performance", "react"],
        relevanceDisplay: "1.8k stars",
      },
      {
        evidenceId: "maya-blog-reactive-backends",
        kind: "blog",
        title: "Designing reactive backends without custom socket infra",
        snippet:
          "Wrote about using event-driven state and subscription invalidation to simplify realtime product delivery.",
        url: "https://example.com/maya/reactive-backends",
        strength: 0.84,
        recencyYears: 0.9,
        tags: ["convex", "realtime", "developer tools", "distributed systems"],
        relevanceDisplay: "240 reactions",
      },
      {
        evidenceId: "maya-talk-devtools",
        kind: "talk",
        title: "From product ergonomics to platform reliability",
        snippet:
          "Conference talk connecting frontend velocity, internal tooling, and distributed product quality.",
        url: "https://www.youtube.com/watch?v=example-maya-devtools",
        strength: 0.76,
        recencyYears: 1.2,
        tags: ["devtools", "frontend performance", "platform"],
        relevanceDisplay: "12k views",
      },
    ],
  },
  {
    slug: "julian-ortega",
    fullName: "Julian Ortega",
    headline: "Principal Engineer for distributed systems and AI infrastructure",
    summary:
      "Deep infra engineer with strong systems and observability experience. Less product-leaning, but excellent on distributed execution and backend architecture.",
    location: "Berlin, Germany",
    currentCompany: "Threadgraph",
    profileUrl: "https://www.linkedin.com/in/julian-ortega-example",
    email: "julian@example.com",
    warmIntroPath: "You -> Nia (operator) -> Julian",
    age: 41,
    yearsExperience: 13,
    seniority: "principal",
    stacks: ["Go", "Rust", "TypeScript", "Kubernetes", "Postgres", "Kafka"],
    domains: ["infrastructure", "ai", "platform"],
    roleKeywords: ["principal engineer", "distributed systems", "platform", "infra"],
    signalConfidence: 0.9,
    reachabilityScore: 0.68,
    companyLogoUrl: companyLogo("threadgraph.com"),
    socialGithub: "github.com/julian-ortega",
    socialBlog: "julian.dev",
    socialTwitter: "@julian_o",
    networkConnections: [
      {
        id: "jul-c1",
        name: "Nia Park",
        avatar: avatarUrl("nia-park"),
        role: "operator @ seed fund",
        channels: [{ type: "conference", detail: "systems week 2024" }],
        strength: "strong",
        lastInteraction: "3 weeks ago",
        sharedProjects: 1,
        relationship: "intro path",
      },
      {
        id: "jul-c2",
        name: "Omar Reyes",
        avatar: avatarUrl("omar-reyes"),
        role: "principal engineer @ threadgraph",
        channels: [
          { type: "company", detail: "reporting line overlap" },
          { type: "github", detail: "scheduler reviews" },
        ],
        strength: "medium",
        lastInteraction: "6 weeks ago",
        sharedProjects: 4,
        relationship: "former teammate",
      },
    ],
    evidence: [
      {
        evidenceId: "julian-repo-scheduler",
        kind: "repo",
        title: "Distributed job scheduler",
        snippet:
          "Maintainer of an OSS scheduler optimized for low-latency task fan-out and fault tolerance.",
        url: "https://github.com/example/julian/scheduler",
        strength: 0.95,
        recencyYears: 0.5,
        tags: ["distributed systems", "infrastructure", "open source", "performance"],
        relevanceDisplay: "890 stars",
      },
      {
        evidenceId: "julian-blog-multi-tenant",
        kind: "blog",
        title: "Hard lessons from multi-tenant execution",
        snippet:
          "Detailed write-up on queue isolation, noisy neighbors, and runtime guardrails for shared compute.",
        url: "https://www.reddit.com/r/golang/comments/example-julian-multitenant",
        strength: 0.82,
        recencyYears: 1.4,
        tags: ["distributed systems", "ai", "infrastructure"],
        relevanceDisplay: "1.4k upvotes",
      },
      {
        evidenceId: "julian-community-sre",
        kind: "community",
        title: "SRE and platform mentor",
        snippet: "Frequently mentors infra teams on architecture reviews and scaling incidents.",
        strength: 0.64,
        recencyYears: 1.8,
        tags: ["community", "platform", "leadership"],
      },
    ],
  },
  {
    slug: "alina-patel",
    fullName: "Alina Patel",
    headline: "Senior React engineer focused on product UX and performance",
    summary:
      "Excellent frontend and product engineer with strong React taste, performance experience, and some developer tooling exposure.",
    location: "Amsterdam, Netherlands",
    currentCompany: "Canvasloop",
    profileUrl: "https://www.linkedin.com/in/alina-patel-example",
    email: "alina@example.com",
    age: 32,
    yearsExperience: 8,
    seniority: "senior",
    stacks: ["React", "TypeScript", "Next.js", "GraphQL"],
    domains: ["design tooling", "collaboration", "productivity"],
    roleKeywords: ["senior frontend engineer", "react", "product engineer"],
    signalConfidence: 0.79,
    reachabilityScore: 0.42,
    companyLogoUrl: companyLogo("canvasloop.com"),
    socialGithub: "github.com/alina-patel",
    socialBlog: "alinap.design",
    socialTwitter: "@alinap",
    networkConnections: [
      {
        id: "ali-c1",
        name: "Priya Nair",
        avatar: avatarUrl("priya-nair"),
        role: "design lead @ canvasloop",
        channels: [{ type: "company", detail: "product pod" }],
        strength: "strong",
        lastInteraction: "1 month ago",
        sharedProjects: 5,
        relationship: "colleague",
      },
    ],
    evidence: [
      {
        evidenceId: "alina-repo-editor-performance",
        kind: "repo",
        title: "Large-canvas performance work",
        snippet:
          "Profiled and rewrote critical rendering paths for a collaborative design editor.",
        url: "https://github.com/example/alina/editor-perf",
        strength: 0.87,
        recencyYears: 0.6,
        tags: ["react", "performance", "frontend", "collaboration"],
        relevanceDisplay: "412 stars",
      },
      {
        evidenceId: "alina-blog-design-systems",
        kind: "blog",
        title: "Design systems for product velocity",
        snippet:
          "Shows mature product thinking but less explicit backend or distributed systems depth.",
        url: "https://example.com/alina/design-systems",
        strength: 0.61,
        recencyYears: 1.1,
        tags: ["react", "product", "design systems"],
      },
    ],
  },
  {
    slug: "samir-haddad",
    fullName: "Samir Haddad",
    headline: "Engineering manager turned player-coach for AI product teams",
    summary:
      "Strong cross-functional operator with AI product experience and credible backend depth, but less hands-on recent OSS evidence.",
    location: "Paris, France",
    currentCompany: "Northsignal AI",
    profileUrl: "https://www.linkedin.com/in/samir-haddad-example",
    email: "samir@example.com",
    warmIntroPath: "You -> Elena (founder) -> Samir",
    age: 44,
    yearsExperience: 12,
    seniority: "manager",
    stacks: ["Python", "TypeScript", "React", "Postgres"],
    domains: ["ai", "productivity", "b2b saas"],
    roleKeywords: ["engineering manager", "player coach", "ai products"],
    signalConfidence: 0.71,
    reachabilityScore: 0.76,
    companyLogoUrl: companyLogo("northsignal.com"),
    socialGithub: "github.com/samir-haddad",
    socialBlog: "samir.ai",
    socialTwitter: "@samir_h",
    networkConnections: [
      {
        id: "sam-c1",
        name: "Elena Voss",
        avatar: avatarUrl("elena-voss"),
        role: "founder",
        channels: [
          { type: "conference", detail: "warm intro path" },
          { type: "company", detail: "advisor board" },
        ],
        strength: "strong",
        lastInteraction: "2 weeks ago",
        sharedProjects: 4,
        relationship: "founder",
      },
    ],
    evidence: [
      {
        evidenceId: "samir-employment-ai",
        kind: "employment",
        title: "Led AI workflow platform launch",
        snippet:
          "Owned a team building workflow automation with strong customer iteration speed.",
        url: "https://www.linkedin.com/in/samir-haddad-example/details/experience",
        strength: 0.8,
        recencyYears: 0.8,
        tags: ["ai", "product", "leadership"],
        relevanceDisplay: "42 skills endorsed",
      },
      {
        evidenceId: "samir-network-intro",
        kind: "network",
        title: "Warm founder path",
        snippet:
          "Two-step path from your existing network to a trusted founder who has worked directly with Samir.",
        strength: 0.75,
        recencyYears: 0.2,
        tags: ["network", "warm intro", "reachability"],
      },
    ],
  },
  {
    slug: "nora-kim",
    fullName: "Nora Kim",
    headline: "Senior backend engineer for fintech APIs and data platforms",
    summary:
      "Great backend operator with strong reliability patterns and customer-facing API work, though less aligned with developer tooling and React-heavy roles.",
    location: "Dublin, Ireland",
    currentCompany: "Ledgerflow",
    profileUrl: "https://www.linkedin.com/in/nora-kim-example",
    email: "nora@example.com",
    age: 35,
    yearsExperience: 9,
    seniority: "senior",
    stacks: ["TypeScript", "Node.js", "Postgres", "Kafka"],
    domains: ["fintech", "data", "backend"],
    roleKeywords: ["backend engineer", "api", "data platform"],
    signalConfidence: 0.85,
    reachabilityScore: 0.38,
    companyLogoUrl: companyLogo("ledgerflow.com"),
    socialGithub: "github.com/nora-kim",
    socialBlog: "nora.engineering",
    socialTwitter: "@norak",
    networkConnections: [
      {
        id: "nor-c1",
        name: "Chris Doyle",
        avatar: avatarUrl("chris-doyle"),
        role: "sre lead",
        channels: [{ type: "slack", detail: "incident channel" }],
        strength: "medium",
        lastInteraction: "1 month ago",
        sharedProjects: 2,
        relationship: "colleague",
      },
      {
        id: "nor-c2",
        name: "Ines Costa",
        avatar: avatarUrl("ines-costa"),
        role: "staff engineer @ ledgerflow",
        channels: [{ type: "company", detail: "platform team" }],
        strength: "weak",
        lastInteraction: "4 months ago",
        sharedProjects: 1,
        relationship: "cross-team",
      },
    ],
    evidence: [
      {
        evidenceId: "nora-repo-api-platform",
        kind: "repo",
        title: "Evented API platform",
        snippet:
          "Implemented transactional event pipelines, reconciliation, and observability for financial APIs.",
        url: "https://github.com/example/nora/evented-api",
        strength: 0.9,
        recencyYears: 0.7,
        tags: ["backend", "fintech", "distributed systems", "typescript"],
        relevanceDisplay: "2.1k stars",
      },
      {
        evidenceId: "nora-talk-reliability",
        kind: "talk",
        title: "Reliability patterns for regulated systems",
        snippet:
          "Strong systems taste, but not much evidence of frontend or devtools product work.",
        url: "https://www.youtube.com/watch?v=example-nora-reliability",
        strength: 0.69,
        recencyYears: 1.5,
        tags: ["backend", "fintech", "reliability"],
        relevanceDisplay: "8.4k views",
      },
    ],
  },
  {
    slug: "leo-santos",
    fullName: "Leo Santos",
    headline: "Open source maintainer building DX for data and APIs",
    summary:
      "Developer-experience specialist with strong writing and OSS proof, though a bit more API and platform than collaborative UI.",
    location: "Lisbon, Portugal",
    currentCompany: "Querydock",
    profileUrl: "https://www.linkedin.com/in/leo-santos-example",
    email: "leo@example.com",
    warmIntroPath: "You -> Priya (investor) -> Leo",
    age: 36,
    yearsExperience: 10,
    seniority: "staff",
    stacks: ["TypeScript", "React", "Node.js", "GraphQL", "Postgres"],
    domains: ["devtools", "apis", "data"],
    roleKeywords: ["staff engineer", "developer experience", "open source"],
    signalConfidence: 0.88,
    reachabilityScore: 0.73,
    companyLogoUrl: companyLogo("querydock.com"),
    socialGithub: "github.com/leo-santos",
    socialBlog: "leo.dev",
    socialTwitter: "@leosantos",
    networkConnections: [
      {
        id: "leo-c1",
        name: "Priya Shah",
        avatar: avatarUrl("priya-shah"),
        role: "investor",
        channels: [{ type: "conference", detail: "devtools summit" }],
        strength: "strong",
        lastInteraction: "3 weeks ago",
        sharedProjects: 2,
        relationship: "investor intro",
      },
      {
        id: "leo-c2",
        name: "Dan Wu",
        avatar: avatarUrl("dan-wu"),
        role: "maintainer @ oss",
        channels: [
          { type: "oss", detail: "shared RFCs" },
          { type: "github", detail: "co-maintainer" },
        ],
        strength: "medium",
        lastInteraction: "5 weeks ago",
        sharedProjects: 3,
        relationship: "oss collaborator",
      },
    ],
    evidence: [
      {
        evidenceId: "leo-repo-dx-cli",
        kind: "repo",
        title: "API workflow CLI",
        snippet:
          "Maintains a popular open source CLI that simplifies developer workflows around APIs and local testing.",
        url: "https://github.com/example/leo/dx-cli",
        strength: 0.9,
        recencyYears: 0.3,
        tags: ["devtools", "open source", "typescript", "developer tools"],
        relevanceDisplay: "4.6k stars",
      },
      {
        evidenceId: "leo-blog-documentation",
        kind: "blog",
        title: "Why great developer docs change adoption curves",
        snippet:
          "Strong evidence of communication, product thinking, and empathy for technical users.",
        url: "https://example.com/leo/dev-docs",
        strength: 0.74,
        recencyYears: 0.5,
        tags: ["devtools", "writing", "product", "developer experience"],
      },
      {
        evidenceId: "leo-community-maintainer",
        kind: "community",
        title: "Maintainer office hours",
        snippet: "Hosts public office hours for OSS users and contributors.",
        url: "https://www.reddit.com/r/typescript/comments/example-leo-office-hours",
        strength: 0.67,
        recencyYears: 0.4,
        tags: ["community", "open source", "developer tools"],
        relevanceDisplay: "312 upvotes",
      },
    ],
  },
];

