import type { CandidateStub } from "./ranking";

export const candidateStubs: CandidateStub[] = [
  {
    slug: "maya-chen",
    fullName: "Maya Chen",
    headline: "Staff Full-Stack Engineer building realtime developer tools",
    summary:
      "Builds developer-facing products with React, TypeScript, and realtime backends. Has led product and infra work for collaboration features and observable systems.",
    location: "London, UK",
    currentCompany: "Mergeboard",
    profileUrl: "https://example.com/maya-chen",
    email: "maya@example.com",
    warmIntroPath: "You -> Ravi (angel) -> Maya",
    yearsExperience: 11,
    seniority: "staff",
    stacks: ["React", "TypeScript", "Convex", "Node.js", "Postgres", "WebSockets"],
    domains: ["devtools", "realtime", "collaboration"],
    roleKeywords: ["staff engineer", "full-stack", "developer tools", "realtime systems"],
    signalConfidence: 0.92,
    reachabilityScore: 0.8,
    evidence: [
      {
        evidenceId: "maya-repo-realtime-presence",
        kind: "repo",
        title: "Presence service for multiplayer editing",
        snippet:
          "Led a production presence and cursor-sync service handling high fan-out collaboration sessions.",
        url: "https://github.com/example/maya/presence-service",
        strength: 0.96,
        recencyYears: 0.4,
        tags: ["realtime", "websockets", "collaboration", "performance", "react"],
      },
      {
        evidenceId: "maya-blog-reactive-backends",
        kind: "blog",
        title: "Designing reactive backends without custom socket infra",
        snippet:
          "Wrote about using event-driven state and subscription invalidation to simplify realtime product delivery.",
        url: "https://example.com/maya/reactive-backends",
        strength: 0.84,
        recencyYears: 0.9,
        tags: ["convex", "realtime", "developer tools", "distributed systems"],
      },
      {
        evidenceId: "maya-talk-devtools",
        kind: "talk",
        title: "From product ergonomics to platform reliability",
        snippet:
          "Conference talk connecting frontend velocity, internal tooling, and distributed product quality.",
        strength: 0.76,
        recencyYears: 1.2,
        tags: ["devtools", "frontend performance", "platform"],
      },
    ],
  },
  {
    slug: "julian-ortega",
    fullName: "Julian Ortega",
    headline: "Principal Engineer for distributed systems and AI infrastructure",
    summary:
      "Deep infra engineer with strong systems and observability experience. Less product-leaning, but excellent on distributed execution and backend architecture.",
    location: "Berlin, Germany",
    currentCompany: "Threadgraph",
    profileUrl: "https://example.com/julian-ortega",
    email: "julian@example.com",
    warmIntroPath: "You -> Nia (operator) -> Julian",
    yearsExperience: 13,
    seniority: "principal",
    stacks: ["Go", "Rust", "TypeScript", "Kubernetes", "Postgres", "Kafka"],
    domains: ["infrastructure", "ai", "platform"],
    roleKeywords: ["principal engineer", "distributed systems", "platform", "infra"],
    signalConfidence: 0.9,
    reachabilityScore: 0.68,
    evidence: [
      {
        evidenceId: "julian-repo-scheduler",
        kind: "repo",
        title: "Distributed job scheduler",
        snippet:
          "Maintainer of an OSS scheduler optimized for low-latency task fan-out and fault tolerance.",
        url: "https://github.com/example/julian/scheduler",
        strength: 0.95,
        recencyYears: 0.5,
        tags: ["distributed systems", "infrastructure", "open source", "performance"],
      },
      {
        evidenceId: "julian-blog-multi-tenant",
        kind: "blog",
        title: "Hard lessons from multi-tenant execution",
        snippet:
          "Detailed write-up on queue isolation, noisy neighbors, and runtime guardrails for shared compute.",
        url: "https://example.com/julian/multi-tenant-execution",
        strength: 0.82,
        recencyYears: 1.4,
        tags: ["distributed systems", "ai", "infrastructure"],
      },
      {
        evidenceId: "julian-community-sre",
        kind: "community",
        title: "SRE and platform mentor",
        snippet: "Frequently mentors infra teams on architecture reviews and scaling incidents.",
        strength: 0.64,
        recencyYears: 1.8,
        tags: ["community", "platform", "leadership"],
      },
    ],
  },
  {
    slug: "alina-patel",
    fullName: "Alina Patel",
    headline: "Senior React engineer focused on product UX and performance",
    summary:
      "Excellent frontend and product engineer with strong React taste, performance experience, and some developer tooling exposure.",
    location: "Amsterdam, Netherlands",
    currentCompany: "Canvasloop",
    profileUrl: "https://example.com/alina-patel",
    email: "alina@example.com",
    yearsExperience: 8,
    seniority: "senior",
    stacks: ["React", "TypeScript", "Next.js", "GraphQL"],
    domains: ["design tooling", "collaboration", "productivity"],
    roleKeywords: ["senior frontend engineer", "react", "product engineer"],
    signalConfidence: 0.79,
    reachabilityScore: 0.42,
    evidence: [
      {
        evidenceId: "alina-repo-editor-performance",
        kind: "repo",
        title: "Large-canvas performance work",
        snippet:
          "Profiled and rewrote critical rendering paths for a collaborative design editor.",
        url: "https://github.com/example/alina/editor-perf",
        strength: 0.87,
        recencyYears: 0.6,
        tags: ["react", "performance", "frontend", "collaboration"],
      },
      {
        evidenceId: "alina-blog-design-systems",
        kind: "blog",
        title: "Design systems for product velocity",
        snippet:
          "Shows mature product thinking but less explicit backend or distributed systems depth.",
        url: "https://example.com/alina/design-systems",
        strength: 0.61,
        recencyYears: 1.1,
        tags: ["react", "product", "design systems"],
      },
    ],
  },
  {
    slug: "samir-haddad",
    fullName: "Samir Haddad",
    headline: "Engineering manager turned player-coach for AI product teams",
    summary:
      "Strong cross-functional operator with AI product experience and credible backend depth, but less hands-on recent OSS evidence.",
    location: "Paris, France",
    currentCompany: "Northsignal AI",
    profileUrl: "https://example.com/samir-haddad",
    email: "samir@example.com",
    warmIntroPath: "You -> Elena (founder) -> Samir",
    yearsExperience: 12,
    seniority: "manager",
    stacks: ["Python", "TypeScript", "React", "Postgres"],
    domains: ["ai", "productivity", "b2b saas"],
    roleKeywords: ["engineering manager", "player coach", "ai products"],
    signalConfidence: 0.71,
    reachabilityScore: 0.76,
    evidence: [
      {
        evidenceId: "samir-employment-ai",
        kind: "employment",
        title: "Led AI workflow platform launch",
        snippet:
          "Owned a team building workflow automation with strong customer iteration speed.",
        strength: 0.8,
        recencyYears: 0.8,
        tags: ["ai", "product", "leadership"],
      },
      {
        evidenceId: "samir-network-intro",
        kind: "network",
        title: "Warm founder path",
        snippet:
          "Two-step path from your existing network to a trusted founder who has worked directly with Samir.",
        strength: 0.75,
        recencyYears: 0.2,
        tags: ["network", "warm intro", "reachability"],
      },
    ],
  },
  {
    slug: "nora-kim",
    fullName: "Nora Kim",
    headline: "Senior backend engineer for fintech APIs and data platforms",
    summary:
      "Great backend operator with strong reliability patterns and customer-facing API work, though less aligned with developer tooling and React-heavy roles.",
    location: "Dublin, Ireland",
    currentCompany: "Ledgerflow",
    profileUrl: "https://example.com/nora-kim",
    email: "nora@example.com",
    yearsExperience: 9,
    seniority: "senior",
    stacks: ["TypeScript", "Node.js", "Postgres", "Kafka"],
    domains: ["fintech", "data", "backend"],
    roleKeywords: ["backend engineer", "api", "data platform"],
    signalConfidence: 0.85,
    reachabilityScore: 0.38,
    evidence: [
      {
        evidenceId: "nora-repo-api-platform",
        kind: "repo",
        title: "Evented API platform",
        snippet:
          "Implemented transactional event pipelines, reconciliation, and observability for financial APIs.",
        url: "https://github.com/example/nora/evented-api",
        strength: 0.9,
        recencyYears: 0.7,
        tags: ["backend", "fintech", "distributed systems", "typescript"],
      },
      {
        evidenceId: "nora-talk-reliability",
        kind: "talk",
        title: "Reliability patterns for regulated systems",
        snippet:
          "Strong systems taste, but not much evidence of frontend or devtools product work.",
        strength: 0.69,
        recencyYears: 1.5,
        tags: ["backend", "fintech", "reliability"],
      },
    ],
  },
  {
    slug: "leo-santos",
    fullName: "Leo Santos",
    headline: "Open source maintainer building DX for data and APIs",
    summary:
      "Developer-experience specialist with strong writing and OSS proof, though a bit more API and platform than collaborative UI.",
    location: "Lisbon, Portugal",
    currentCompany: "Querydock",
    profileUrl: "https://example.com/leo-santos",
    email: "leo@example.com",
    warmIntroPath: "You -> Priya (investor) -> Leo",
    yearsExperience: 10,
    seniority: "staff",
    stacks: ["TypeScript", "React", "Node.js", "GraphQL", "Postgres"],
    domains: ["devtools", "apis", "data"],
    roleKeywords: ["staff engineer", "developer experience", "open source"],
    signalConfidence: 0.88,
    reachabilityScore: 0.73,
    evidence: [
      {
        evidenceId: "leo-repo-dx-cli",
        kind: "repo",
        title: "API workflow CLI",
        snippet:
          "Maintains a popular open source CLI that simplifies developer workflows around APIs and local testing.",
        url: "https://github.com/example/leo/dx-cli",
        strength: 0.9,
        recencyYears: 0.3,
        tags: ["devtools", "open source", "typescript", "developer tools"],
      },
      {
        evidenceId: "leo-blog-documentation",
        kind: "blog",
        title: "Why great developer docs change adoption curves",
        snippet:
          "Strong evidence of communication, product thinking, and empathy for technical users.",
        url: "https://example.com/leo/dev-docs",
        strength: 0.74,
        recencyYears: 0.5,
        tags: ["devtools", "writing", "product", "developer experience"],
      },
      {
        evidenceId: "leo-community-maintainer",
        kind: "community",
        title: "Maintainer office hours",
        snippet: "Hosts public office hours for OSS users and contributors.",
        strength: 0.67,
        recencyYears: 0.4,
        tags: ["community", "open source", "developer tools"],
      },
    ],
  },
];

